package fr.esgi.projet.softwareneedsyou;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasANiceName() {
        App classUnderTest = new App();
        assertEquals("class fr.esgi.projet.softwareneedsyou.App", classUnderTest.getClass().toString());
    }
}
