package fr.esgi.projet.softwareneedsyou;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(final String[] args) {
    	init();
    	final App app = new App();
        System.out.println(app.getGreeting());
    }
    
    /**
     * Initialise la JVM avant le lancement de l'application
     */
    public final static void init() {
    	//create folder if not existe
    	if(Files.notExists(SharedParams.AppParamsFolder)) {
    		System.out.println("// create app folders");
    		try {
				Files.createDirectories(SharedParams.AppParamsFolder);
				Files.createDirectories(SharedParams.AppPluginsFolder);
			} catch (IOException e) {
				e.printStackTrace();
			}
    	} else
    		System.out.println("// App folder exists");
    	// set classpath
    	String jcp = System.getProperty("java.class.path");
    	System.out.println("Old classpath : " + jcp);
    	System.setProperty("java.class.path", jcp + File.pathSeparator + SharedParams.AppPluginsFolder + File.separator + "*");
    }
}
