package fr.esgi.projet.softwareneedsyou;

import java.io.File;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(final String[] args) {
    	init();
    	final App app = new App();
        System.out.println(app.getGreeting());
    }
    
    /**
     * Initialise la JVM avant le lancement de l'application
     */
    private static void init() {
    	String jcp = System.getProperty("java.class.path");
    	System.out.println("Old classpath : " + jcp);
    	System.setProperty("java.class.path", jcp + File.pathSeparator + SharedParams.AppPluginsFolder + File.separator + "*");
    }
}
