package fr.esgi.projet.softwareneedsyou.api;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Tmp {
    public String getGreeting() {
        return "Hello world.";
    }
}
