package fr.esgi.projet.softwareneedsyou.api;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class TmpTest {
    @Test public void testTmpHasAGreeting() {
        Tmp classUnderTest = new Tmp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
